version: '3'

services:
  traefik:
    image: "traefik:latest"
    container_name: "traefik-p51"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-ssl-certs:/ssl-certs
    networks:
      - traefik-public-p51
    env_file:
      - .env
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
          max-file: "5"
          max-size: "10m"




networks:
  traefik-public-p51:
    driver: bridge


volumes:
  traefik-ssl-certs:
    driver: local